"use client";
import React,{useState} from "react";
import {Phone,Mail,MapPin,Users,Building2,Home,Shield,ArrowRight,Printer,Globe,Search} from "lucide-react";
const BRAND={name:"Area Co Real Estate",gradientFrom:"#d414a4",gradientTo:"#4b1ea8",address:"8400 NW 33rd St, Doral, FL 33122",phone:"786.863.3549",fax:"1.866.882.1210",email:"gabriel@myarearealtor.com",tagline:"Licensed to serve you with all your real estate needs throughout the state of Florida.",logo:"/logo.png"};
const Section=({id,children}:{id:string,children:React.ReactNode})=>(<section id={id} className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-14">{children}</section>);
const GradientText=({children}:{children:React.ReactNode})=>(<span className="bg-clip-text text-transparent" style={{backgroundImage:`linear-gradient(135deg, ${BRAND.gradientFrom}, ${BRAND.gradientTo})`}}>{children}</span>);
const NavButton=({label,active,onClick,icon:Icon}:{label:string,active:boolean,onClick:()=>void,icon:any})=> (<button onClick={onClick} className={`inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-semibold transition-all ${active?"scale-100":"opacity-80 hover:opacity-100"}`} style={{background:active?`linear-gradient(135deg, ${BRAND.gradientFrom}, ${BRAND.gradientTo})`:'#ffffff',color:active?'white':'#2b1b3f'}}><Icon size={16}/>{label}</button>);
const Header=({current,setCurrent}:{current:string,setCurrent:(s:string)=>void})=>(<header className="sticky top-0 z-40 backdrop-blur bg-white/70 border-b border-white/40"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-3 flex items-center justify-between"><div className="flex items-center gap-3"><img src={BRAND.logo} alt="Logo" width={36} height={36} className="rounded-full"/><div className="leading-tight"><div className="font-black text-lg tracking-tight">{BRAND.name}</div><div className="text-xs text-neutral-600">{BRAND.tagline}</div></div></div><nav className="flex items-center gap-2"><NavButton label="Home" icon={Home} active={current==='home'} onClick={()=>setCurrent('home')}/><NavButton label="MLS Search" icon={Search} active={current==='search'} onClick={()=>setCurrent('search')}/><NavButton label="About" icon={Building2} active={current==='about'} onClick={()=>setCurrent('about')}/></nav></div></header>);
const Hero=()=>(<div className="relative overflow-hidden"><div className="absolute inset-0 -z-10" style={{background:`linear-gradient(135deg, ${BRAND.gradientFrom}, ${BRAND.gradientTo})`}}/><Section id="home"><div className="grid lg:grid-cols-2 gap-10 items-center text-white"><div><h1 className="text-4xl sm:text-5xl font-black leading-tight">Your <GradientText>Miami</GradientText> Experts — Real Estate Across <GradientText>Florida</GradientText></h1><p className="mt-4 text-white/90 max-w-prose">We help buyers, sellers, and investors navigate South Florida and beyond with clarity and confidence.</p></div><div className="rounded-3xl shadow-2xl p-1 bg-white/10"><div className="rounded-3xl p-8 bg-white text-neutral-900"><div className="flex items-start gap-3"><MapPin className="mt-1"/><div><div className="font-semibold">Headquarters</div><div className="text-sm">{BRAND.address}</div><div className="mt-2 flex flex-col gap-1 text-sm"><a href={`tel:${BRAND.phone.replace(/\D/g,'')}`} className="inline-flex items-center gap-2 hover:underline"><Phone size={14}/> {BRAND.phone}</a><a href={`mailto:${BRAND.email}`} className="inline-flex items-center gap-2 hover:underline"><Mail size={14}/> {BRAND.email}</a><div className="inline-flex items-center gap-2"><Printer size={14}/> Fax: {BRAND.fax}</div></div></div></div></div></div></div></Section></div>);
const MLSSearch=()=>(<Section id="search"><div className="text-center mb-8"><h2 className="text-3xl font-black tracking-tight">Live MLS <GradientText>Search</GradientText></h2><p className="text-neutral-600 mt-2">Browse active listings directly from our MLS feed.</p></div><div className="w-full h-[80vh] rounded-2xl overflow-hidden border shadow"><div className="p-2 bg-neutral-50 text-neutral-700 text-sm flex items-center justify-between"><span>If the live search doesn't display, use the button.</span><a href="https://sef.mlsmatrix.com/Matrix/public/IDX.aspx?idx=725b1018" target="_blank" rel="noopener" className="px-3 py-1 rounded-lg text-white" style={{background:`linear-gradient(135deg, ${BRAND.gradientFrom}, ${BRAND.gradientTo})`}}>Open MLS Search</a></div><iframe title="MLS IDX Search" src="https://sef.mlsmatrix.com/Matrix/public/IDX.aspx?idx=725b1018" width="100%" height="100%" frameBorder={0} className="w-full h-full" loading="lazy"/></div></Section>);
const Footer=()=>(<footer className="mt-10"><div className="py-10" style={{background:`linear-gradient(135deg, ${BRAND.gradientFrom}, ${BRAND.gradientTo})`}}><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-white grid sm:grid-cols-2 gap-8"><div><div className="font-black text-lg">{BRAND.name}</div><div className="text-white/90 text-sm mt-1">{BRAND.tagline}</div></div><div className="text-sm"><div className="font-semibold">Contact</div><div className="mt-1">{BRAND.address}</div><div className="mt-1">Phone: <a className="underline" href={`tel:${BRAND.phone.replace(/\D/g,'')}`}>{BRAND.phone}</a></div><div className="mt-1">Fax: {BRAND.fax}</div><div className="mt-1">Email: <a className="underline" href={`mailto:${BRAND.email}`}>{BRAND.email}</a></div></div></div></div><div className="bg-neutral-950 text-white/70 text-xs py-3 text-center">© {new Date().getFullYear()} {BRAND.name}. All rights reserved.</div></footer>);
export default function Page(){const [current,setCurrent]=useState('home');return(<div className="min-h-screen"><Header current={current} setCurrent={setCurrent}/>{current==='home'&&<Hero/>}{current==='search'&&<MLSSearch/>}<Footer/></div>);}